baseURL = "https://dwalkr.github.io/sawmill/"
languageCode = "en-us"
theme = "sawmill"
title = "Microsite"

[Author]
name = "Performics"

[[menu.main]]
name = "Case Studies"
url = "#section1"
weight = 1

[[menu.main]]
name = "Presentations"
url = "#section2"
weight = 2

[[menu.main]]
name = "Media Feature"
url = "#section3"
weight = 3

[[menu.main]]
name = "Team"
url = "#section4"
weight = 4

[params]
logo = "/logo.svg"
